sudo: true
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
script:
- export EXPLORER_LOG_PATH="log.txt"
- cmake -H. -B_builds -DCPACK_GENERATOR=DEB
- cmake --build _builds
- cmake --build _builds --target package
- cd _builds
- ./explorer CMakeCache.txt
- cd ..
- mv _builds/*.tar.gz artifacts
