sudo: true
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
script:
- export EXPLORER_LOG_PATH="log.txt"
- make -j 2
- cmake --build _build --target package
- cd _build
- ./explorer CMakeCache.txt
- cd ..
- mv _build/*.tar.gz artifacts
